
enum SCENEID { SCENE_TITLE, SCENE_LOGO, SCENE_STAGE, SCENE_STAGE2 };

enum ORTHOGONAL { D3DTS_ORTHOGONAL = 4 };

enum PLAYERINFO { PLAYER_POS = 10, PLAYER_DIR = 11, PLAYER_HP = 12, PLAYER_BULLET = 13, PLAYER_STATE = 14, PLAYER_WORLD = 15, PLAYER_MAXBOARDNUM = 16, PLAYER_BOARDNUM = 17};

enum TERRAINTYPE { TERRAIN_FRONT, TERRAIN_MID, TERRAIN_BACK, TERRAIN_CLIFFLEFT, TERRAIN_CLIFFRIGHT, TERRAIN_SKY, TERRAIN_FORESKY };

enum HELI_TERRAIN_COL_DIR{COL_LEFT,COL_RIGHT,COL_END};

enum OBJ_STATE {LIVE,DIE};

enum BUL_TYPE { BUL_BASIC, BUL_MULTI, BUL_MISILE, BUL_BOMB };
enum WEAPON_TYPE { WEAPON_GUN, WEAPON_GATLELING, WEAPON_LAUNCHER, };

enum HOOK_TYPE{PLAYER_HOOK,FREIGHT_HOOK};

enum SOUNDTYPE {SOUND_TITLE, SOUND_GAMEPLAY, SOUND_BUTTON, SOUND_GUN, SOUND_GAMEEFFECT};